-- Add last_contacted column and backfill from Monday.com data
ALTER TABLE private_wire_leads ADD COLUMN IF NOT EXISTS last_contacted DATE;

UPDATE private_wire_leads SET last_contacted = '2026-03-02' WHERE name = 'Aggregate Industries';
UPDATE private_wire_leads SET last_contacted = '2026-03-03' WHERE name = 'Augean';
UPDATE private_wire_leads SET last_contacted = '2026-03-03' WHERE name = 'Biffa';
UPDATE private_wire_leads SET last_contacted = '2026-03-02' WHERE name = 'CELTIC ENERGY';
UPDATE private_wire_leads SET last_contacted = '2026-03-02' WHERE name = 'Cemex UK (quarry group)';
UPDATE private_wire_leads SET last_contacted = '2026-03-02' WHERE name = 'Cynon Valley Waste Disposal Company Ltd (trading as Amgen Cymru) (e.g., Bryn Pica)';
UPDATE private_wire_leads SET last_contacted = '2026-03-30' WHERE name = 'Enovert';
UPDATE private_wire_leads SET last_contacted = '2026-03-02' WHERE name = 'Enva';
UPDATE private_wire_leads SET last_contacted = '2026-03-02' WHERE name = 'FCC Environment';
UPDATE private_wire_leads SET last_contacted = '2026-02-17' WHERE name = 'Grundon Waste Management';
UPDATE private_wire_leads SET last_contacted = '2026-03-02' WHERE name = 'Hanson (Heidelberg Materials)';
UPDATE private_wire_leads SET last_contacted = '2026-03-02' WHERE name = 'Newport City Council';
UPDATE private_wire_leads SET last_contacted = '2026-02-19' WHERE name = 'Suez UK';
UPDATE private_wire_leads SET last_contacted = '2026-03-02' WHERE name = 'Tarmac';
UPDATE private_wire_leads SET last_contacted = '2026-03-03' WHERE name = 'The Mick George Group (Heidelberg)';
UPDATE private_wire_leads SET last_contacted = '2026-02-19' WHERE name = 'Valencia Waste Management';
UPDATE private_wire_leads SET last_contacted = '2026-02-18' WHERE name = 'Viridor';
UPDATE private_wire_leads SET last_contacted = '2026-03-26' WHERE name = 'Albion Stone';
UPDATE private_wire_leads SET last_contacted = '2026-03-26' WHERE name = 'Breedon Group';
UPDATE private_wire_leads SET last_contacted = '2026-03-02' WHERE name = 'Brett Group';
UPDATE private_wire_leads SET last_contacted = '2026-03-26' WHERE name = 'Buxton Lime / Johnston Quarry Group';
UPDATE private_wire_leads SET last_contacted = '2026-02-17' WHERE name = 'Cemex UK';
UPDATE private_wire_leads SET last_contacted = '2026-03-26' WHERE name = 'Colas Ltd (UK)';
UPDATE private_wire_leads SET last_contacted = '2026-03-26' WHERE name = 'Encirc (Vidrala)';
UPDATE private_wire_leads SET last_contacted = '2026-03-26' WHERE name = 'FM Conway';
UPDATE private_wire_leads SET last_contacted = '2026-03-02' WHERE name = 'Forterra';
UPDATE private_wire_leads SET last_contacted = '2026-02-17' WHERE name = 'Heidelberg Materials UK';
UPDATE private_wire_leads SET last_contacted = '2026-03-02' WHERE name = 'Hillhouse Quarry Group';
UPDATE private_wire_leads SET last_contacted = '2026-03-02' WHERE name = 'Holcim UK';
UPDATE private_wire_leads SET last_contacted = '2026-03-02' WHERE name = 'Leiths Group';
UPDATE private_wire_leads SET last_contacted = '2026-03-26' WHERE name = 'Lhoist UK';
UPDATE private_wire_leads SET last_contacted = '2026-03-02' WHERE name = 'Saint-Gobain';
UPDATE private_wire_leads SET last_contacted = '2026-03-26' WHERE name = 'Singleton Birch';
UPDATE private_wire_leads SET last_contacted = '2026-02-17' WHERE name = 'Tarmac (CRH)';
UPDATE private_wire_leads SET last_contacted = '2026-03-02' WHERE name = 'Tillicoultry Quarries';
UPDATE private_wire_leads SET last_contacted = '2026-03-26' WHERE name = 'Wienerberger UK';
UPDATE private_wire_leads SET last_contacted = '2026-02-25' WHERE name = 'British Steel';
UPDATE private_wire_leads SET last_contacted = '2026-02-25' WHERE name = 'Liberty Steel (UK operations)';
UPDATE private_wire_leads SET last_contacted = '2026-02-25' WHERE name = 'Sheffield Forgemasters';
UPDATE private_wire_leads SET last_contacted = '2026-02-25' WHERE name = 'Tata Steel UK';
UPDATE private_wire_leads SET last_contacted = '2026-02-25' WHERE name = 'Cemex UK (Quarry';
UPDATE private_wire_leads SET last_contacted = '2026-02-25' WHERE name = 'AF Blakemore & Son Ltd';
UPDATE private_wire_leads SET last_contacted = '2026-03-02' WHERE name = 'Aldi UK';
UPDATE private_wire_leads SET last_contacted = '2026-03-23' WHERE name = 'Americold';
UPDATE private_wire_leads SET last_contacted = '2026-02-17' WHERE name = 'Arla Foods';
UPDATE private_wire_leads SET last_contacted = '2026-03-23' WHERE name = 'Asda';
UPDATE private_wire_leads SET last_contacted = '2026-03-23' WHERE name = 'Best Food Logisitcs';
UPDATE private_wire_leads SET last_contacted = '2026-03-23' WHERE name = 'Bidfood UK';
UPDATE private_wire_leads SET last_contacted = '2026-03-02' WHERE name = 'Booker (Tesco Wholesale)';
UPDATE private_wire_leads SET last_contacted = '2026-03-23' WHERE name = 'Brakes';
UPDATE private_wire_leads SET last_contacted = '2026-03-02' WHERE name = 'CEVA Logistics';
UPDATE private_wire_leads SET last_contacted = '2026-03-23' WHERE name = 'Co-op';
UPDATE private_wire_leads SET last_contacted = '2026-03-24' WHERE name = 'Constellation Cold Logistics';
UPDATE private_wire_leads SET last_contacted = '2026-03-24' WHERE name = 'Culina Group Limited';
UPDATE private_wire_leads SET last_contacted = '2026-03-24' WHERE name = 'DFDS';
UPDATE private_wire_leads SET last_contacted = '2026-03-24' WHERE name = 'DP World';
UPDATE private_wire_leads SET last_contacted = '2026-03-24' WHERE name = 'EV Cargo';
UPDATE private_wire_leads SET last_contacted = '2026-03-24' WHERE name = 'Flamingo Horticulture';
UPDATE private_wire_leads SET last_contacted = '2026-03-30' WHERE name = 'Fowler Welch (Culina)';
UPDATE private_wire_leads SET last_contacted = '2026-03-24' WHERE name = 'FreshLinc';
UPDATE private_wire_leads SET last_contacted = '2026-03-24' WHERE name = 'Gist Limited';
UPDATE private_wire_leads SET last_contacted = '2026-03-30' WHERE name = 'Great Bear Distribution (Culina)';
UPDATE private_wire_leads SET last_contacted = '2026-04-07' WHERE name = 'Greencore';
UPDATE private_wire_leads SET last_contacted = '2026-03-30' WHERE name = 'Greggs';
UPDATE private_wire_leads SET last_contacted = '2026-03-30' WHERE name = 'Gregory Group';
UPDATE private_wire_leads SET last_contacted = '2026-04-07' WHERE name = 'GXO Logistics, Inc.';
UPDATE private_wire_leads SET last_contacted = '2026-03-30' WHERE name = 'Iceland Foods';
UPDATE private_wire_leads SET last_contacted = '2026-03-02' WHERE name = 'John Lewis';
UPDATE private_wire_leads SET last_contacted = '2026-03-30' WHERE name = 'Kuehne+Nagel';
UPDATE private_wire_leads SET last_contacted = '2026-03-30' WHERE name = 'Langdons';
UPDATE private_wire_leads SET last_contacted = '2026-03-27' WHERE name = 'Magnavale Ltd';
UPDATE private_wire_leads SET last_contacted = '2026-03-30' WHERE name = 'Marks & Spencer';
UPDATE private_wire_leads SET last_contacted = '2026-03-30' WHERE name = 'Morrisons';
UPDATE private_wire_leads SET last_contacted = '2026-03-02' WHERE name = 'Müller UK & Ireland';
UPDATE private_wire_leads SET last_contacted = '2026-03-02' WHERE name = 'NewCold';
UPDATE private_wire_leads SET last_contacted = '2026-03-02' WHERE name = 'Ocado';
UPDATE private_wire_leads SET last_contacted = '2026-03-02' WHERE name = 'Reed Boardall';
UPDATE private_wire_leads SET last_contacted = '2026-03-02' WHERE name = 'Sainsbury''s';
UPDATE private_wire_leads SET last_contacted = '2026-03-03' WHERE name = 'Samworth Brothers';
UPDATE private_wire_leads SET last_contacted = '2026-03-02' WHERE name = 'Stobart (Culina)';
UPDATE private_wire_leads SET last_contacted = '2026-03-02' WHERE name = 'Tesco';
UPDATE private_wire_leads SET last_contacted = '2026-03-02' WHERE name = 'Turners (Soham) Ltd';
UPDATE private_wire_leads SET last_contacted = '2026-04-07' WHERE name = 'XPO Logistics';
UPDATE private_wire_leads SET last_contacted = '2026-03-02' WHERE name = 'AB InBev';
UPDATE private_wire_leads SET last_contacted = '2026-03-03' WHERE name = 'Ardagh Group';
UPDATE private_wire_leads SET last_contacted = '2026-03-03' WHERE name = 'Valeo Foods UK';
UPDATE private_wire_leads SET last_contacted = '2026-03-03' WHERE name = '2 Sisters Food Group';
UPDATE private_wire_leads SET last_contacted = '2026-03-03' WHERE name = 'Cranswick Country Foods';
UPDATE private_wire_leads SET last_contacted = '2026-03-05' WHERE name = 'Samworth Brothers (X2)';
UPDATE private_wire_leads SET last_contacted = '2026-03-03' WHERE name = 'Moy Park';
UPDATE private_wire_leads SET last_contacted = '2026-03-03' WHERE name = 'ABP Food Group';
UPDATE private_wire_leads SET last_contacted = '2026-03-03' WHERE name = 'Premier Foods';
UPDATE private_wire_leads SET last_contacted = '2026-03-03' WHERE name = 'Soreen (Samworth Bros)';
UPDATE private_wire_leads SET last_contacted = '2026-03-03' WHERE name = 'Hovis (Associated British Foods)';
UPDATE private_wire_leads SET last_contacted = '2026-03-03' WHERE name = 'Warburtons';
UPDATE private_wire_leads SET last_contacted = '2026-03-03' WHERE name = 'Allied Bakeries (ABF)';
