// Supabase Edge Function: push-to-notion
// Creates an IC Memo page in Notion under the Acquisitions workspace.
// Requires NOTION_API_KEY secret set in Supabase.

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const NOTION_API_URL = "https://api.notion.com/v1/pages";
const NOTION_VERSION = "2022-06-28";

// Acquisitions parent page in Fuse Energy Notion workspace
const DEFAULT_PARENT_PAGE_ID = "f5d58f09-c465-4fb0-be45-875d98c7c623";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

// ── Notion block builders ──────────────────────────────────────────────────

function heading2(text: string): object {
  return {
    object: "block",
    type: "heading_2",
    heading_2: {
      rich_text: [{ type: "text", text: { content: text } }],
      is_toggleable: true,
    },
  };
}

function heading3(text: string): object {
  return {
    object: "block",
    type: "heading_3",
    heading_3: {
      rich_text: [{ type: "text", text: { content: text } }],
    },
  };
}

function bulletItem(text: string, bold = false): object {
  return {
    object: "block",
    type: "bulleted_list_item",
    bulleted_list_item: {
      rich_text: [
        {
          type: "text",
          text: { content: text },
          annotations: { bold },
        },
      ],
    },
  };
}

function labelValueBullet(label: string, value: string): object {
  return {
    object: "block",
    type: "bulleted_list_item",
    bulleted_list_item: {
      rich_text: [
        {
          type: "text",
          text: { content: `${label}: ` },
          annotations: { bold: true, underline: true },
        },
        {
          type: "text",
          text: { content: value },
        },
      ],
    },
  };
}

function paragraph(text: string): object {
  return {
    object: "block",
    type: "paragraph",
    paragraph: {
      rich_text: [{ type: "text", text: { content: text } }],
    },
  };
}

function divider(): object {
  return { object: "block", type: "divider", divider: {} };
}

function richParagraph(segments: Array<{ text: string; bold?: boolean; italic?: boolean; color?: string }>): object {
  return {
    object: "block",
    type: "paragraph",
    paragraph: {
      rich_text: segments.map((s) => ({
        type: "text",
        text: { content: s.text },
        annotations: {
          bold: s.bold || false,
          italic: s.italic || false,
          color: s.color || "default",
        },
      })),
    },
  };
}

// ── Table builder ──────────────────────────────────────────────────────────

function tableBlock(headers: string[], rows: string[][]): object {
  const allRows = [headers, ...rows];
  return {
    object: "block",
    type: "table",
    table: {
      table_width: headers.length,
      has_column_header: true,
      has_row_header: false,
      children: allRows.map((row) => ({
        object: "block",
        type: "table_row",
        table_row: {
          cells: row.map((cell) => [
            { type: "text", text: { content: cell || "—" } },
          ]),
        },
      })),
    },
  };
}

// ── Format helpers ─────────────────────────────────────────────────────────

const fmt = (n: number | null, d = 1): string =>
  n == null ? "—" : Number(n).toFixed(d);

const fmtM = (n: number | null): string => {
  if (!n) return "—";
  const abs = Math.abs(n);
  if (abs >= 1000000) return `£${(n / 1000000).toFixed(1)}m`;
  if (abs >= 1000) return `£${(n / 1000).toFixed(1)}k`;
  return `£${n.toFixed(0)}`;
};

// ── Build the IC Memo blocks ───────────────────────────────────────────────

function buildMemoBlocks(project: any, data: any): object[] {
  const { latestRun, inputMap, comps } = data;
  const blocks: object[] = [];

  // Header info
  blocks.push(
    richParagraph([
      { text: "CONFIDENTIAL", bold: true },
      { text: " | Generated by Fuse Platform | " },
      {
        text: new Date().toLocaleDateString("en-GB", {
          day: "numeric",
          month: "long",
          year: "numeric",
        }),
      },
    ])
  );
  blocks.push(divider());

  // ── 1. Executive Summary (toggle heading) ──────────────────────────────
  const execChildren: object[] = [];
  execChildren.push(labelValueBullet("Project", project.name || "—"));
  execChildren.push(labelValueBullet("Technology", project.technology || "—"));
  execChildren.push(labelValueBullet("Location", project.geography || "—"));
  execChildren.push(
    labelValueBullet(
      "Capacity",
      project.capacity_mwp ? `${project.capacity_mwp} MWp` : "—"
    )
  );
  execChildren.push(
    labelValueBullet(
      "Project IRR",
      latestRun?.project_irr ? `${fmt(latestRun.project_irr)}%` : "—"
    )
  );
  execChildren.push(
    labelValueBullet(
      "Equity IRR",
      latestRun?.equity_irr ? `${fmt(latestRun.equity_irr)}%` : "—"
    )
  );
  execChildren.push(
    labelValueBullet(
      "Total CapEx",
      latestRun?.total_capex ? fmtM(latestRun.total_capex) : "—"
    )
  );
  execChildren.push(
    labelValueBullet(
      "NPV",
      latestRun?.project_npv ? fmtM(latestRun.project_npv) : "—"
    )
  );
  execChildren.push(
    labelValueBullet(
      "Min DSCR",
      latestRun?.min_dscr ? `${fmt(latestRun.min_dscr)}x` : "—"
    )
  );

  // Recommendation
  const irrOk = latestRun?.project_irr && latestRun.project_irr >= 7.5;
  const dscrOk = !latestRun?.min_dscr || latestRun.min_dscr >= 1.25;
  let recText = "Below hurdle rate - further analysis required";
  let recEmoji = "⚠️";
  if (irrOk && dscrOk) {
    recText = "Approved - meets investment hurdle rate";
    recEmoji = "✅";
  } else if (irrOk) {
    recText = "Conditional - IRR meets target, DSCR needs review";
    recEmoji = "🟡";
  }
  execChildren.push(labelValueBullet("Recommendation", `${recText} ${recEmoji}`));

  blocks.push({
    object: "block",
    type: "heading_2",
    heading_2: {
      rich_text: [{ type: "text", text: { content: "Executive Summary" } }],
      is_toggleable: true,
      children: execChildren,
    },
  });

  // ── 2. Project Overview (toggle heading) ───────────────────────────────
  const overviewChildren: object[] = [];
  overviewChildren.push(labelValueBullet("Project Name", project.name || "—"));
  overviewChildren.push(labelValueBullet("Technology", project.technology || "—"));
  overviewChildren.push(labelValueBullet("Geography", project.geography || "—"));
  overviewChildren.push(
    labelValueBullet(
      "Capacity",
      project.capacity_mwp ? `${project.capacity_mwp} MWp` : "—"
    )
  );
  overviewChildren.push(
    labelValueBullet("COD", project.cod || inputMap?.cod || "—")
  );
  overviewChildren.push(labelValueBullet("Status", project.status || "—"));
  overviewChildren.push(
    labelValueBullet(
      "Gearing",
      project.gearing ? `${project.gearing}%` : "—"
    )
  );

  if (inputMap) {
    overviewChildren.push(heading3("Key Assumptions"));
    overviewChildren.push(
      labelValueBullet(
        "P50 Yield",
        inputMap.yield_kwh ? `${inputMap.yield_kwh} kWh/kWp` : "—"
      )
    );
    overviewChildren.push(
      labelValueBullet(
        "Degradation",
        inputMap.degradation ? `${inputMap.degradation}% p.a.` : "—"
      )
    );
    overviewChildren.push(
      labelValueBullet(
        "Export Capacity",
        inputMap.export_mw ? `${inputMap.export_mw} MW` : "—"
      )
    );
    overviewChildren.push(
      labelValueBullet(
        "Grid Costs",
        inputMap.grid_costs ? fmtM(Number(inputMap.grid_costs)) : "—"
      )
    );
    overviewChildren.push(
      labelValueBullet(
        "Opex",
        inputMap.opex_per_mw
          ? `£${Number(inputMap.opex_per_mw).toFixed(0)}/MW`
          : "—"
      )
    );
  }

  blocks.push({
    object: "block",
    type: "heading_2",
    heading_2: {
      rich_text: [{ type: "text", text: { content: "Project Overview" } }],
      is_toggleable: true,
      children: overviewChildren,
    },
  });

  // ── 3. Financial Summary (toggle heading) ──────────────────────────────
  const finChildren: object[] = [];
  if (latestRun) {
    finChildren.push(heading3("Returns"));
    finChildren.push(
      labelValueBullet(
        "Project IRR (unlevered)",
        latestRun.project_irr ? `${fmt(latestRun.project_irr)}%` : "—"
      )
    );
    finChildren.push(
      labelValueBullet(
        "Equity IRR (levered)",
        latestRun.equity_irr ? `${fmt(latestRun.equity_irr)}%` : "—"
      )
    );
    finChildren.push(
      labelValueBullet(
        "Project NPV",
        latestRun.project_npv ? fmtM(latestRun.project_npv) : "—"
      )
    );
    finChildren.push(
      labelValueBullet(
        "Minimum DSCR",
        latestRun.min_dscr ? `${fmt(latestRun.min_dscr)}x` : "—"
      )
    );

    finChildren.push(heading3("Capital Structure"));
    finChildren.push(
      labelValueBullet("Total CapEx", fmtM(latestRun.total_capex))
    );
    const equity = latestRun.total_capex
      ? latestRun.total_capex * (1 - (project.gearing || 70) / 100)
      : null;
    finChildren.push(
      labelValueBullet("Equity Required", equity ? fmtM(equity) : "—")
    );
    finChildren.push(
      labelValueBullet("Gearing", project.gearing ? `${project.gearing}%` : "70%")
    );
    finChildren.push(
      labelValueBullet(
        "Total Distributions",
        latestRun.total_distributions
          ? fmtM(latestRun.total_distributions * 1000)
          : "—"
      )
    );

    finChildren.push(heading3("Revenue Breakdown"));
    finChildren.push(
      labelValueBullet(
        "CfD Revenue",
        latestRun.cfd_rev ? fmtM(latestRun.cfd_rev * 1000) : "—"
      )
    );
    finChildren.push(
      labelValueBullet(
        "PPA Revenue",
        latestRun.ppa_rev ? fmtM(latestRun.ppa_rev * 1000) : "—"
      )
    );
    finChildren.push(
      labelValueBullet(
        "Merchant Revenue",
        latestRun.merchant_rev ? fmtM(latestRun.merchant_rev * 1000) : "—"
      )
    );
    finChildren.push(
      labelValueBullet(
        "REGO Revenue",
        latestRun.rego_rev ? fmtM(latestRun.rego_rev * 1000) : "—"
      )
    );
  } else {
    finChildren.push(paragraph("No financial model run available for this project."));
  }

  blocks.push({
    object: "block",
    type: "heading_2",
    heading_2: {
      rich_text: [{ type: "text", text: { content: "Financial Summary" } }],
      is_toggleable: true,
      children: finChildren,
    },
  });

  // ── 4. Comparable Transactions (toggle heading) ────────────────────────
  if (comps && comps.length > 0) {
    const compRows = comps.map((c: any) => {
      const ccy = c.currency === "EUR" ? "€" : c.currency === "USD" ? "$" : "£";
      return [
        (c.project_name || "—").substring(0, 30),
        c.geography || "—",
        c.capacity_mw ? fmt(c.capacity_mw, 0) : "—",
        c.stage || "—",
        c.price_per_mw ? `${ccy}${Math.round(c.price_per_mw / 1000)}k` : "—",
        c.implied_irr ? `${fmt(c.implied_irr)}%` : "—",
      ];
    });

    const compsTable = tableBlock(
      ["Transaction", "Geography", "MW", "Stage", "£/MW", "IRR"],
      compRows
    );

    blocks.push({
      object: "block",
      type: "heading_2",
      heading_2: {
        rich_text: [
          { type: "text", text: { content: "Comparable Transactions" } },
        ],
        is_toggleable: true,
        children: [
          paragraph(
            `Recent ${project.technology} transactions providing market context:`
          ),
          compsTable,
        ],
      },
    });
  }

  // ── 5. Key Risks (toggle heading) ──────────────────────────────────────
  const riskChildren: object[] = [];

  // Auto-generated risks
  if (latestRun?.project_irr && latestRun.project_irr < 7.5) {
    riskChildren.push(heading3("Below-hurdle Returns"));
    riskChildren.push(
      paragraph(
        `Project IRR of ${fmt(latestRun.project_irr)}% is below the 7.5% target hurdle rate. Requires either value engineering on CapEx or improved revenue assumptions to meet investment criteria.`
      )
    );
  }
  if (latestRun?.min_dscr && latestRun.min_dscr < 1.25) {
    riskChildren.push(heading3("Debt Service Coverage"));
    riskChildren.push(
      paragraph(
        `Minimum DSCR of ${fmt(latestRun.min_dscr)}x is tight and may not meet lender covenants (typically 1.25x minimum). Consider adjusting gearing or tenor.`
      )
    );
  }
  if (
    latestRun?.merchant_rev &&
    latestRun.cfd_rev &&
    latestRun.merchant_rev > latestRun.cfd_rev
  ) {
    riskChildren.push(heading3("Merchant Revenue Exposure"));
    riskChildren.push(
      paragraph(
        "A significant portion of revenue is uncontracted (merchant). Power price volatility could materially impact returns."
      )
    );
  }
  if (project.status === "RtB") {
    riskChildren.push(heading3("Construction Risk"));
    riskChildren.push(
      paragraph(
        "Project is at Ready-to-Build stage. Construction delays, EPC contractor performance, and supply chain disruptions could impact COD timing and returns."
      )
    );
  }

  // Standard risks
  riskChildren.push(heading3("Planning & Permitting"));
  riskChildren.push(
    paragraph(
      "Risk of planning conditions, judicial review, or community opposition that could delay or prevent development."
    )
  );
  riskChildren.push(heading3("Grid Connection"));
  riskChildren.push(
    paragraph(
      "Dependency on grid connection timeline and costs. Risk of connection delays, curtailment, or constraint charges."
    )
  );
  riskChildren.push(heading3("Power Price Risk"));
  riskChildren.push(
    paragraph(
      "Long-term power price forecasts are inherently uncertain. Downside scenarios should be stress-tested against base case returns."
    )
  );

  blocks.push({
    object: "block",
    type: "heading_2",
    heading_2: {
      rich_text: [{ type: "text", text: { content: "Key Risks" } }],
      is_toggleable: true,
      children: riskChildren,
    },
  });

  // ── 6. Recommendation (toggle heading) ─────────────────────────────────
  const recChildren: object[] = [];
  if (irrOk && dscrOk) {
    recChildren.push(
      paragraph(
        `Based on the financial analysis, ${project.name} meets the investment hurdle rate with a Project IRR of ${fmt(latestRun.project_irr)}% and adequate debt service coverage. The project is recommended for IC approval to proceed to the next stage of the acquisition process.`
      )
    );
  } else if (irrOk) {
    recChildren.push(
      paragraph(
        `${project.name} achieves the target IRR of ${fmt(latestRun?.project_irr)}%, however debt service metrics require further review. Conditional approval is recommended, subject to refinancing analysis.`
      )
    );
  } else {
    recChildren.push(
      paragraph(
        `${project.name} currently falls below the target hurdle rate. Further value engineering or improved commercial terms are recommended before seeking IC approval.`
      )
    );
  }

  blocks.push({
    object: "block",
    type: "heading_2",
    heading_2: {
      rich_text: [{ type: "text", text: { content: "Recommendation" } }],
      is_toggleable: true,
      children: recChildren,
    },
  });

  return blocks;
}

// ── Main handler ───────────────────────────────────────────────────────────

serve(async (req: Request) => {
  // CORS preflight
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const NOTION_API_KEY = Deno.env.get("NOTION_API_KEY");
    if (!NOTION_API_KEY) {
      return new Response(
        JSON.stringify({ error: "NOTION_API_KEY not configured" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const { project, data, parentPageId } = await req.json();

    if (!project || !data) {
      return new Response(
        JSON.stringify({ error: "Missing project or data in request body" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const parentId = parentPageId || DEFAULT_PARENT_PAGE_ID;
    const blocks = buildMemoBlocks(project, data);

    // Create the Notion page
    const dateStr = new Date().toISOString().split("T")[0];
    const title = `📋 ${project.name} - IC Memo (${dateStr})`;

    const notionResponse = await fetch(NOTION_API_URL, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${NOTION_API_KEY}`,
        "Notion-Version": NOTION_VERSION,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        parent: { type: "page_id", page_id: parentId },
        icon: { type: "emoji", emoji: "📋" },
        properties: {
          title: {
            title: [{ type: "text", text: { content: title } }],
          },
        },
        children: blocks,
      }),
    });

    if (!notionResponse.ok) {
      const errBody = await notionResponse.text();
      console.error("Notion API error:", errBody);
      return new Response(
        JSON.stringify({
          error: "Notion API error",
          details: errBody,
          status: notionResponse.status,
        }),
        {
          status: notionResponse.status,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        }
      );
    }

    const result = await notionResponse.json();

    return new Response(
      JSON.stringify({
        success: true,
        pageId: result.id,
        url: result.url,
      }),
      {
        status: 200,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  } catch (err) {
    console.error("Error in push-to-notion:", err);
    return new Response(
      JSON.stringify({ error: err.message }),
      {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  }
});
